version: '3.5'

volumes:
  data:

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: AdsEnterpriseDB
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/