version: '3.5'

volumes:
  data:
  
services:
  db:
    container_name: mysql_container
    image: mysql:8.0.21
    restart: always
    networks:
      my-network:
        ipv4_address: 172.16.238.2 
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=adsDb
      - MYSQL_USER=acesso
      - MYSQL_PASSWORD=acesso
    ports:
      - "3306:3306"
    volumes:
      - ./dataContainer:/var/lib/mysql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/29