version: '3.5'

volumes:
  data:

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    networks:
      my-network:
        ipv4_address: 172.16.238.2 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: AdsEnterpriseDB
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/29